name: Java-Jar and Maven CI

on:
  push:
    branches:
      - main 
jobs:
    build-jar:

        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Log in to GitHub container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.DOJO_USER_TOKEN }}

        - name: Lowercase the repo name
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

        - name: Build and push container image to registry
          uses: docker/build-push-action@v4
          with:
           push: true
           tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
           file: ./Dockerfile
          
        - name: Authenticate with GitHub Packages
          run: | 
            mkdir -p ~/.m2
            echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{github.actor}}</username>
                <password>${{ secrets.DOJO_USER_TOKEN }}</password>
              </server>
            </servers>
            </settings>" > ~/.m2/settings.xml

        - name: Publish to GitHub Packages
          run: mvn deploy -Dmaven.test.skip=true
