name: CI Java Lib

on:
  push:
    branches:
      - main 
jobs:
  build-java-lib:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 11 (ou outra versão necessária)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Baixar Deps
        run: |
          mvn -f ./project/pom.xml clean install  

      - name: Build with Maven
        run: mvn -B package --file project/pom.xml

      # Upload .jar as a build artifact
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-app.jar
          path: target/*.jar

      # Authenticate with GitHub Packages using GITHUB_TOKEN
      - name: Authenticate with GitHub Packages
        run: |
          mkdir -p ~/.m2 
          echo "//maven.pkg.github.com/${{ github.repository }}=${{ secrets.DOJO_USER_TOKEN }}" >> ~/.m2/settings.xml 

      # Publish to GitHub Packages
      - name: Publish package to GitHub Packages
        run: mvn deploy -Dmaven.test.skip=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }}

        

