name: Java and Maven CI

on:
  push:
    branches:
      - main 
jobs:
    build-image-docker:

        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: build docker image
          run: docker build -t ghcr.io/${{github.repository}}/dojojava:latest .

        - name: push docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ghcr.io/${{github.repository}}/dojojava:latest
    

        
        