name: CI Java Lib

on:
  push:
    branches:
      - main 
jobs:
  build-java-lib:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 11 (ou outra versão necessária)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Baixar Deps
        run: |
          mvn -f ./project/pom.xml clean install  

      - name: Build with Maven
        run: mvn -B package --file project/pom.xml

      # Upload .jar as a build artifact
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: my-app.jar
          path: target/*.jar

      # Authenticate with GitHub Packages using GITHUB_TOKEN
      - name: Authenticate with GitHub Packages
        run: |
          mkdir -p ~/.m2 
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>\${{ github.actor }}</username>
                <password>\${{ secrets.DOJO_USER_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Publish to GitHub Packages
      - name: Publish package to GitHub Packages
        run: mvn deploy

        

