name: Java and Maven CI

on:
  push:
    branches:
      - main 
jobs:
    build-image-docker:
        env:
           WORK_DIR_TMP: /tmp
    
        runs-on: ubuntu-latest    

        container: maven:3.6.3-jdk-11

        steps:
        - uses: actions/checkout@v4

        - name: action docker login
          uses: azure/docker-login@v1
          with:
            login-server: 'docker.io'
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: build docker image
          run: docker build -t javadojo .
    
        