name: CI Java Lib

on:
  push:
    branches:
      - main 
jobs:
  build-java-lib:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 11 (ou outra versão necessária)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Baixar Deps
        run: |
          mvn -f ./project/pom.xml clean install  

      - name: List
        run: |
          ls -la

      - name: Build with Maven
        run: mvn -B package --file ./project/pom.xml

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        

