name: CI Java Lib

on:
  push:
    branches:
      - main 

jobs:
  build-java-lib:
    env:
          GITHUB_TOKEN: ${{ secrets.DOJO_GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: | 
          mvn -B package --file ./project/pom.xml          
          mvn deploy:deploy-file \
            -Dfile=./project/target/demo-0.0.1-SNAPSHOT.jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/juliobsilva/java-dojo \
            -DgroupId=com.example \
            -DartifactId=demo \
            -Dversion=1.0.0 \
            -Dpackaging=jar
            -Dusername=${{ github.actor }} \
            -Dpassword=${{ secrets.DOJO_USER_TOKEN }}