name: Java and Maven CI

on:
  push:
    branches:
      - main 
jobs:
    build-image-docker:

        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        - name: build docker image
          run: docker build -t img-java-dojo:latest .

        - name: Log in to GitHub container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.DOJO_USER_TOKEN }}

        - name: Push Docker image
          run: docker push ghcr.io/${{ github.repository }}/img-java-dojo:latest
    

        
        