name: CI/CD Java Web Api

on:
  workflow_dispatch:
  push:
    paths:
      - 'src-java-webapi/**'

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-java.yaml
    with:
      app-path: ./src-java-webapi
      
  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./src-java-webapi/target

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOJO_USER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./src-java-webapi/         
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

